// document
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_TAG  = 'CHANGE_TAG';

export const FETCH_DOCUMENT_REQUEST = 'FETCH_DOCUMENT_REQUEST';
export const FETCH_DOCUMENT_SUCCESS = 'FETCH_DOCUMENT_SUCCESS';
export const FETCH_DOCUMENT_FAILED  = 'FETCH_DOCUMENT_FAILED';



// viewer
// - nav
export const OPEN_NAV  = 'OPEN_NAV'
export const CLOSE_NAV = 'CLOSE_NAV'

// - create
export const CHANGE_NEW_PATH     = 'CHANGE_NEW_PATH'
export const OPEN_CREATE_DIALOG  = 'OPEN_CREATE_DIALOG'
export const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG'

export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const CREATE_DOCUMENT_FAILED  = 'CREATE_DOCUMENT_FAILED'

// - delete
export const OPEN_DELETE_DIALOG  = 'OPEN_DELETE_DIALOG'
export const CLOSE_DELETE_DIALOG = 'CLOSE_DELETE_DIALOG'

export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST'
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS'
export const DELETE_DOCUMENT_FAILED  = 'DELETE_DOCUMENT_FAILED'



// editor
// - save
export const SAVE_DOCUMENT_REQUEST = 'SAVE_DOCUMENT_REQUEST'
export const SAVE_DOCUMENT_SUCCESS = 'SAVE_DOCUMENT_SUCCESS'
export const SAVE_DOCUMENT_FAILED  = 'SAVE_DOCUMENT_FAILED'

export const OPEN_SAVE_DOCUMENT_NOTIFICATION  = 'OPEN_SAVE_DOCUMENT_NOTIFICATION'
export const CLOSE_SAVE_DOCUMENT_NOTIFICATION = 'CLOSE_SAVE_DOCUMENT_NOTIFICATION'


// - image
export const OPEN_IMAGE_LIST  = 'OPEN_IMAGE_LIST'
export const CLOSE_IMAGE_LIST = 'CLOSE_IMAGE_LIST'

export const FETCH_IMAGE_LIST_REQUEST = 'FETCH_IMAGE_LIST_REQUEST'
export const FETCH_IMAGE_LIST_SUCCESS = 'FETCH_IMAGE_LIST_SUCCESS'
export const FETCH_IMAGE_LIST_FAILED  = 'FETCH_IMAGE_LIST_FAILED'

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILED  = 'UPLOAD_IMAGE_FAILED'

export const OPEN_UPLOAD_IMAGE_NOTIFICATION  = 'OPEN_UPLOAD_IMAGE_NOTIFICATION'
export const CLOSE_UPLOAD_IMAGE_NOTIFICATION = 'CLOSE_UPLOAD_IMAGE_NOTIFICATION'


// - tag
export const OPEN_TAG_EDIT  = 'OPEN_TAG_EDIT'
export const CLOSE_TAG_EDIT = 'CLOSE_TAG_EDIT'

export const FETCH_TAG_OPTIONS_REQUEST = 'FETCH_TAG_OPTIONS_REQUEST'
export const FETCH_TAG_OPTIONS_SUCCESS = 'FETCH_TAG_OPTIONS_SUCCESS'
export const FETCH_TAG_OPTIONS_FAILED  = 'FETCH_TAG_OPTIONS_FAILE'


// - command
export const OPEN_COMMAND_TABLE = 'OPEN_COMMAND_TABLE'
export const CLOSE_COMMAND_TABLE = 'CLOSE_COMMAND_TABLE'
